name: ART Tarantool Pull Request
on: [ pull_request ]
jobs:
  gradle-build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        lua: [ 5.1.5 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: ${{ matrix.lua }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build --max-workers 8 --parallel
